### ISSUE TITLE
[Question] Comparison with Trill

### ISSUE THREAD

**Issue by tadeuszwojcik** [Spreads/Spreads#150]
Hi,
I was looking recently into using `Microsoft/Trill` lib for crypto currencies related streaming analytics, but found yours lib and that got me thinking if perhaps I should give **Spreads** a shot. 
I know Spreads lib is heavily optimized (but not sure if that's relevant if data is coming via websocket and crypto exchanges are lagging a lot), but I haven't seen that many examples of usage of it (esp in c#) so it's quite challenging to get started.

Do you have any thoughts about `Trill` and how it compares with `Spreads`, pros and cons of both? 
I know you're not publishing this project for PR purposes, I respect that and thanks for releasing it anyway.

Cheers,
Tadeusz

**Comment by buybackoff** [comment]
I have opened [an issue](https://github.com/Microsoft/Trill/issues/33) in Trill recently about it's performance tests. The test was not working at all but after the fix it gives unbelievable numbers and empty output, so at the moment I cannot tell which one is faster.

One difference is that Trill (looks like) to work with push model and "temporal data", which requires start and end timestamps, while Spreads works with pull model and `async streams` (upcoming in C# 8.0) and works with a single timestamp+event data. Also Spreads works with a 2D abstraction of data, where time is X-axis, value is Y-axis, and many operations use this representation and allow lazy calculations. The underlying series/containers behave as materialized and **navigable** one and lazy calculations are build on top of them, while IObservable is just a stream of events and one needs to materialize/cache at least a part of them for any calculation. Not sure how Trill works internally, didn't have time to dig into its source code.

Spreads was built for trading/backtesting/financial data initially and there are many patterns covered, e.g. windowing and handling/joining of irregular data. 

Trill uses code generation, which is a big no for me.

Over the past year I also have been working on ACID storage engine, which also has great data compression and fastest IPC possible since it works over shared mmaped data and not via some http server. When combined, I believe the system-wide solution based on Spreads + upcoming storage will be the fastest one because it will be completely integrated - from mmaped disk data to lazy composed operators on top of that, even with zero-copy and no deserialization for blittable data. Trill looks like an engine for calculating data that is already in a certain shape, and as you said getting the data in the required shape is the most expensive process.

Hopefully could release it soon. Now the storage is quite hard to use as a general-purpose one, I used it as a part of crypto-trading infrastructure on my last project. I notices that you have already followed @DataSpreads on Twitter, so stay tuned :) Will appreciate it if you find/give some feedback on how Trill compared to Spreads before I can test it thoroughly myself. And in any case I won't be shy to learn some tricks from Trill and improve Spreads based on that :)

**Comment by buybackoff** [comment]
As for

> but I haven't seen that many examples of usage of it (esp in c#) so it's quite challenging to get started.

I feel ashamed from one side, from another - there are no users I'm aware of besides myself, and it has been challenging to get to stable beta because I cannot devote 100% time to it. Maybe it's catch-22 and without docs no one wants even to try, but without feedback and actionable issues I could only work on my own issues and do not need docs myself since everything is in my head. 

Recently I was focusing on Spreads.Core, with buffer pools, the fastest JSON and binary serialization, etc that was used from the storage level. Basic operators should work, but test coverage is far from 100%.

There are tests with "CI" category and I consider them stable, the tests could be used as examples.

If you give examples of what you want to achieve I could help with Spreads implementation in this thread.

**Comment by tadeuszwojcik** [comment]
Great, thank you for taking your time and such thoughtful response.
I think I prefer `IAsyncEnumerable` interface that this lib offers (vs Trill's ObservableStreamable).
I guess with C# 8, I could consume `Streams` streams it via:

```csharp
await foreach (var insights in insightsStream)
{
                
}
```
Thats the idea, right?

I'd love to learn more how `Streams` lib helps working with windowed data, like sliding window for example (event aggregation in last x seconds/minutes, re-evaluated constantly). I assume that handling irregularities is done via `Repeat`, so that's also completely  different from Trill where `punctuation` events need to be pushed to the stream, (it also does batching by default, it has pros and cons), but it helps with https://github.com/Spreads/Spreads/issues/142 I think - as Trill's query wait's till all input streams produce value for given time - at least from what I understand.

My rough and simplified scenario looks like on diagram below, where there will be streams producer(s) and many various streams that will aggregate stuff based on sliding windows for example, will have to be shared by other streams that will perform computations based on them in different ways (so multi-casting necessary?)
I don't plan to use integrated storage at least currently.
I'm not sure what would be memory usage characteristics of Streams when constantly running and pushing and analyzing new data, would it constantly increase memory usage or would it be constant? Sorry if that's sill question, but it's not obvious for me yet how it works.

I'd love to see even simplest c# example that produces new data constantly and where such data is aggregated/consumed in some way by `Streams` lib, or where there are two streams produced on different intervals and consumed/aggregated together.
I know I'm asking a lot and fully understand if you don't have time for that, no worries. 
Thanks again for quick and awesome reply,
If you'd need help with web dev related stuff in the future (web app, web site) just let me know , I'd be happy to help,
```
                                      +----------+
                                      |Websocket |
                                      |client    |
                                      |connection|
                                      ++--------++
                                       |        |
                                       |        |
                                +------+        +------+
                                |                      |
                                v                      v
                             +--+----+             +---+-----+
                             |Trades |             |Orderbook|
                             |Stream |             |updates  |
                             |       |             |stream   |
                             +-------+             +---------+
                             |                               |
            +----------------+----------+                    |
            |                           |                    +----------------+
            |                           |                                     |
            v                           v                                     |
+-----------+----------+          +-----+-----------+            +------------v-------------+
|Volume imbalance      |          |Volume change    |            |Orderflow imbalance change|
|in last x time periods|          |in last x periods|            |in last x time periods    |
+---------+------------+          +------------+----+            +------------+-------------+
          |                                    |                              |
          |                                    |                              |
          |                                    |                              |
          |                                    |                              |
          |                                    |                              |
          |                                    ^                              |
          |                          +---------+-----------+                  |
          +------------------------> |Stream that produces |                  |
                                     |insights based on    +^-----------------+
                                     |intermediate streams |
                                     +values               |
                                     +---------+-----------+
                                               |
                                               |
                                               |
                                               |
                                               v

```

**Comment by buybackoff** [comment]
I believe you mean `Spreads` lib and not `Streams` one? Will answer later.

**Comment by tadeuszwojcik** [comment]
Ah, sorry, of course I meant `Spreads` -  fixed.

**Comment by buybackoff** [comment]
So far I could run the Trill test only partially and Spreads EquiJoin performance is much better:

* I could get c.10 MOPS in the Trill test if I increase the size of the test by 5x. First run at default size gives c.6MOPS.
* Spreads with SortedMap (single chunk) gives c.17 MOPS
* Spreads with SortedChunkedMap gives c.15 MOPS

```
public static void EquiJoinBench()
        {
            var sml = new SortedMap<long, long>(); // alternative: SortedChunkedMap
            var smr = new SortedMap<long, long>(); // alternative: SortedChunkedMap

            var countl = 1_000_000;
            var step = 10;
            var countr = countl * step;

            for (int i = 0; i < countl; i++)
            {
                sml.Add(i * step, i * step);
            }

            for (int i = 0; i < countr; i++)
            {
                smr.Add(i, i);
            }

            var rounds = 10;

            for (int r = 0; r < rounds; r++)
            {
                var count = 0L;
                var sum = 0L;
                using (Benchmark.Run("EquiJoin", countr))
                {
                    var result = sml.Repeat().Zip(smr, (lv, rv) => lv);

                    foreach (var keyValuePair in result)
                    {
                        sum += keyValuePair.Value;
                        count++;
                    }

                    Console.WriteLine("COUNT: " + count);
                }
            }

            Benchmark.Dump();
        }
```

**Comment by buybackoff** [comment]
@tadeuszwojcik I'm working actively on docs, will cover all you questions soon in a more systematic way soon.

**Comment by tadeuszwojcik** [comment]
Great, thank you, this is really nice, really looking forward to see sample usage of the lib :)
