### ISSUE TITLE
Problem with LinqPad

### ISSUE THREAD

**Issue by ivanfig** [Spreads/Spreads#170]
error FS0229: Error opening binary file 'C:\Users\Ivan Figueredo\AppData\Local\LINQPad\NuGet.FW46\Spreads\Spreads.Collections.2019.0.412\lib\net461\Spreads.Collections.dll': Error reading/writing metadata for the F# compiled DLL 'C:\Users\Ivan Figueredo\AppData\Local\LINQPad\NuGet.FW46\Spreads\Spreads.Collections.2019.0.412\lib\net461\Spreads.Collections.dll'. Was the DLL compiled with an earlier version of the F# compiler? (error: 'u_typ').

error FS3160: Problem reading assembly 'Spreads.Collections, Version=2019.0.0.0, Culture=neutral, PublicKeyToken=eb70e0fec970faf8': Error opening binary file 'C:\Users\Ivan Figueredo\AppData\Local\LINQPad\NuGet.FW46\Spreads\Spreads.Collections.2019.0.412\lib\net461\Spreads.Collections.dll': Error reading/writing metadata for the F# compiled DLL 'C:\Users\Ivan Figueredo\AppData\Local\LINQPad\NuGet.FW46\Spreads\Spreads.Collections.2019.0.412\lib\net461\Spreads.Collections.dll'. Was the DLL compiled with an earlier version of the F# compiler? (error: 'u_typ').

**Comment by ivanfig** [comment]
It would be so much easier if the example program was ported to C#. 90% of us don't know the first thing about f#

http://hotforknowledge.com/2015/12/29/how-to-write-the-simplest-trading-strategy-using-spreads/

**Comment by buybackoff** [comment]
I'm gradually dropping F# in this library, `Spreads.Collections` will be no more. But this is not my day job to work on this project and the only stable container is SortedMap that is implemented in F# so far.

See my comment in #164 for overall status of this library. In short, it's "rework-in-progress", so your only option is to use something else at the moment and watch for `2019.**1**.x` releases. The releases with `2019.**0**.x` version are for infrastructure (buffers management, serialization, etc.).

LinqPad issues are out of scope. Closing for #164

**Comment by ivanfig** [comment]
Thanks for the response. I hear you re: not your day job. IMO, you should set up a voluntary "support this software" option. I bet you get some bucks and makes it less painful to spend your precious time on a high quality library.

**Comment by buybackoff** [comment]
> Thanks for the response. I hear you re: not your day job. IMO, you should set up a voluntary "support this software" option. I bet you get some bucks and makes it less painful to spend your precious time on a high quality library.

Well, it's catch-22. To make it high quality I must release the ideas I have for 2019.**1** (and well-implemented ones). MSFT released [Trill](https://github.com/Microsoft/Trill) and as it goes with .NET ecosystem everything that comes from MSFT is assumed to be high quality and the default choice. So I'm not so sure that I will find enough traction (see the date of the first commit or the blog post you linked) as a general complex event processing system.

I wanted to create a full-stack solution (also see https://github.com/DataSpreads/DataSpreads as persistent layer) but it takes too much time to create a *general purpose* solution. I will keep it specialized and support as much as I can during my free time. But at the moment it's a bag if useful building blocks rather than the full-stack solution.
