### ISSUE TITLE
Drop Lz4 for Zstd

### ISSUE THREAD

**Issue by stocktrader8888** [Spreads/Spreads#64]
Add support for Blosc2.

Blosc2 has support for Zstd which is very impressive in ratios and decompression, and the additional delta filter in addition to the bitshuffling provides extraordinary compression ratios for financial data.  It is now also multithread safe via the contexts.

**Comment by buybackoff** [comment]
Blosc2 is alpha, also they are not adding any groundbreaking stuff, but rather working on containers probably similar to what Spreads offers and what Bcolz did. Zstd is much slower than Lz4, bitshuffling is much slower than byteshuflling and doesn't add visible gains in my tests. See #63, I am completely changing how serialization works and it will be pluggable - you could create a custom serializer for any type. I do not want to add complexity of supporting multiple compression codecs in the core codebase. Also see this [wiki page draft](https://github.com/Spreads/Spreads/wiki/Serialization) for description of the new serialization approach.

**Comment by buybackoff** [comment]
If you could show a real case when algos other than lz4 give much greater compression, I could add ability to change the default compression algo. I played with all of the provided ones, and even zlib doesn't compress much better, just a several percents.

There are much better approach - to use provided `Price` and related data types (which are optimized for Blosc compression) instead of `decimals` and `floats`. But even with decimals, I noticed that after compression `doubles` converted to `decimals` take much less size, because decimals bits are very close to each other when values are close.

**Comment by buybackoff** [comment]
As per multithreading, in Spreads the chunk size is so small that Blosc will not divide the job into parts. Due to the speed of lz4, we are very likely IO-bound anyway.

**Comment by buybackoff** [comment]
With commit 666 one could register any custom converter and it will be backward compatible, i.e. any existing data could be read by using an older converter. This is still WIP, but every needed part is there, just need to make public API.

**Comment by buybackoff** [comment]
@stocktrader8888  I will add Zstd option as a static field of compressor, but will still use Blosc 1 for a while

**Comment by buybackoff** [comment]
On real data - converting 800M ticks to 1M second bars (highest compression in Blosc, byte-shuffle only)

|     | Time          | Size  | Comp Ratio| KOps (Ticks/Bars) |
| ------------- |-------------| -----|-----|------|
| zstd      | 19m 45 s | 814Mb | 4.1 | 709/88 |
| lz4      | 7m 47 sec      |   1256Mb |  2.7 | 1800/223|

For writes the tradeoff is obvious. On synthetic test from SpreadsDB, compression ratio goes from 4.7 to 6.0, writes are also 2+x times slower but reads are on par. In some other tests Zstd reads are even very slightly faster. Therefore, Zstd is good for large data sets that are written once and are read many times.

Nice thing with Blosc is that codec in encoded into the header and the same code could read both Zstd and LZ4 data, which means that we could recompress lz4 into Zsts completely in background when space becomes an issue.

**Comment by buybackoff** [comment]
TODO update this table after IDiffable, LZ4 size was dropped by almost 2x, while speed difference was marginal. The comment with a table above should be a part of docs.

**Comment by buybackoff** [comment]
Zstd with the highest level us very slow, but with level 5 is no slower than lz4 and significantly better comp ration. With Json data Zstd beats Brotli (fastest mode) on synthetic numeric data, while Brotli(optimal) is so awfully slow that it is unusable. 

We should drop support support for Lz4.

Format means preferred - or best-effort - format. Binary means blittable if possible, custom converter if present, Utf8Json for others - all with headers. Json means Utf8Json. Compression applies only for collections for binary using Zstd and for any Json value using standard Gzip (so that browsers could accept it with no additional steps).

**Comment by buybackoff** [comment]
We now do manual shuffle/unshuffle and apply either Zstd or Lz4 or Gzip. Blosc version is no longer a question, we only use shuffling from there and raw compressors for they are conveniently packed and CMake build is easy with just exposing raw routines in existing blosc.c/blosc.h files.

**Comment by buybackoff** [comment]
Spreads.Native has shuffle/unshuffle and native compressors exposed from Blosc compilation. Zstd with level 1 beats LZ4 in average, there are some edge cases when LZ4 is preferrable. Interestingly, GZip over short JSON is often better than Zstd. BinarySerializer writes a header with compressor info and the choice of compressor is exposed to public API. Not an issue anymore.

We do not use bitshuffle, no tests showed its pareto-optimality in speed/ratio or it was very small to bother.
