### ISSUE TITLE
Requesting information about the persistent Map

### ISSUE THREAD

**Issue by karjay** [Spreads/Spreads#95]
Hi,

I was looking to leveraging the memory mapped file-based collections in this project, https://github.com/buybackoff/MMDataStructures, but that GitHub page states that the spreads library has more performant versions. Could you please point me to those collections? The spreads presentation mentions the existence of a persistentMap, but I couldn't find it anywhere in the collections directory.

**Comment by buybackoff** [comment]
Hi, @karjay! 

I removed PersistentDictionary in [666th commit](https://github.com/Spreads/Spreads/commit/dd730b8d3bc2e00c5b1f0405a7d1f37b7e42e83d), because it only supported fixed-sized blittable types at that moment and was kind of out-of-scope for this library. It was very performant though, and I plan to bring it back at some point with new Serialization stuff that I have implemented since then, including the use if the new [Unsafe](https://github.com/dotnet/corefx/tree/master/src/System.Runtime.CompilerServices.Unsafe) package, which together will make it probably event faster. 

As far as I remember, the fixed-size type implementation was quite stable and was a rewrite of `SCG.Dictionary` with generational re-hashing, lock-free IPC concurrency and recovery. I.e. the basic principle was the same - we divide a hash by a prime number number to find a bucket and then do linear search in a array-based linked-list, but instead of re-hashing I just incrementally increase mmaped file and put new records to the incremented place. Lookups suffer theoretically from this, but not that much in practice - and the primary goal was to avoid the big pause during re-hashing in the classic implementation.

You may find [the working version](https://github.com/Spreads/Spreads/blob/69540901c88902f824a48cd3033f9ac3ec19fce5/src/Spreads.Extensions/Storage/PersistentMapFixedLength.cs) in commits right before Aug 11th, 2016. It was GPL2 though at the moment.

As for a general-purpose mmaped data structures - look at LMDB and its .NET [port](https://github.com/CoreyKaylor/Lightning.NET). It's author @hyc did magic with that piece of software, and with in-memory/async workloads it is just impractical to look for anything else, P/Invoke doesn't slow things that much. For a variable-length values PersistentDictionary I would just use LMDB directly (now I use SQLite because I need x86 interop, but usually variable-size values do not require really great performance like blittable structs). And even for fixed-size values there is a trick to use LMDB in [unconventional way](http://www.openldap.org/lists/openldap-technical/201510/msg00133.html) - as a pool of big mmaped buffers instead of separate mmaped files, but it is still on the *long list* of features I want to do.

For fast mmaped IPC, use Aeron and its .NET [port](https://github.com/AdaptiveConsulting/Aeron.NET). It is crazy fast! In the same 666th I deleted an implementation of IPC for Spreads based on my fork of Aeron. I hope to bring that functionality back together with PersistentDictionary "soon", but have no ETA now.

**Comment by buybackoff** [comment]
@karjay  Actually that PersistentDictionary was self-contained, if you are OK with only fixed-sized blittable values, it's a matter of minutes to bring it back here. Could do tomorrow.

**Comment by karjay** [comment]
@buybackoff Thanks for the advice. My scenario required variable-sized values. The value in this case is an object that a string and DateTime as properties. I suppose that will require me to investigate LMDB then?

**Comment by buybackoff** [comment]
Yes, LMDB should be more that enough with proper settings (async for performance). I guess your bottleneck will be serialization anyway, if you need to share such objects among different processes. (even SQLite will work in most cases, there is no a silver bullet)
 
BTW, if your string is bounded in size, check out my latest commit [here](https://github.com/Spreads/Spreads/commit/21530a3f281525259c059f4915ecd91b9250ef25) and SymbolXX structures.

**Comment by karjay** [comment]
@buybackoff I think I can frame my problem such that I need to leverage PersistentMap<int, long>. It turns in my case that the objects I intended to store as values are such that the same value can be assigned to several keys. So, I am better off storing the values in a separate collection and just using a properly designed hascode of the value in the persistentMap.  I would also experiment with LMDB if necessary, but for this use it appears the persistentMap would be very straightforward to leverage.

**Comment by buybackoff** [comment]
Do you want that fixed length impl back here, or you are good with the old version?

**Comment by karjay** [comment]
Yes, please. I would appreciate bringing the fixed length impl back here.

**Comment by buybackoff** [comment]
I said about "minutes"... Probably one day I will learn not to give promises in open-source context. The old version should really work, it depends on `DirectFile` class from SpreadsDB repo (maybe something more from there) in this organization. Sorry for the wrong "minutes" promises, will do "soon".

**Comment by buybackoff** [comment]
Anything persistent will be in @DataSpreads some day
